---
# Per environment values which override defaults in hmpps-content-hub-ui/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    hosts: 
      - content-hub-dev.hmpps.service.justice.gov.uk
      - staff.content-hub-dev.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://content-hub-dev.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    LAUNCHPAD_AUTH_URL: "https://launchpad-auth-dev.hmpps.service.justice.gov.uk"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-dev.prison.service.justice.gov.uk"
    ENVIRONMENT_NAME: DEVELOPMENT
    AUDIT_ENABLED: "false"

generic-prometheus-alerts:
  alertSeverity: hmpps-launchpad-nonprod
